---
driver:
  name: docker
  use_sudo: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

data_bags_path: 'test/integration/data_bags'

suites:
  - name: service-provider
    run_list:
      - recipe[simplesamlphp::service-provider]
    attributes:
